--
-- 5.6.0 to 6.0.0
--
-- Added new dashboard resource
-- Created table JIReportThumbnail to store thumbnails of reports
--
-- Bug 23374 - [case #20392] Large Dashboard elements breaks Postgres
-- Bug 37364 - Platform WAS 7.0.0.31 + Oracle 11g + IBM JDK 1.6: getting an error saving option of chart report
-- Bug 37405 - JBoss 7.1.1 + DB2: Error while saving report options
--

create table JIReportThumbnail (
    id bigint generated by default as identity,
    user_id bigint not null,
    resource_id bigint not null,
    thumbnail blob(20971520) not null,
    primary key (id),
    unique (user_id, resource_id)
);

    alter table JIReportThumbnail
        add constraint FKFDB3DED932282198
        foreign key (user_id)
        references JIUser
        on delete cascade;

    alter table JIReportThumbnail
        add constraint FKFDB3DED9F254B53E
        foreign key (resource_id)
        references JIResource
        on delete cascade;

ALTER TABLE JIDashboardFrameProperty ALTER COLUMN propertyValue SET DATA TYPE varchar(12000);
ALTER TABLE JIJdbcDatasource ALTER COLUMN password SET DATA TYPE varchar(750);
ALTER TABLE JIReportJobRepoDest ALTER COLUMN password SET DATA TYPE varchar(750);
ALTER TABLE JIUser ALTER COLUMN password SET DATA TYPE varchar(750);
ALTER TABLE JIXMLAConnection ALTER COLUMN password SET DATA TYPE varchar(750);

-- change column type from varchar(1000) to clob(400000)
ALTER TABLE JIDashboardFrameProperty ADD COLUMN new_propertyValue clob(400000);
UPDATE JIDashboardFrameProperty SET new_propertyValue = CAST (propertyValue AS clob(400000));
COMMIT;
ALTER TABLE JIDashboardFrameProperty DROP COLUMN propertyValue;
ALTER TABLE JIDashboardFrameProperty RENAME COLUMN new_propertyValue TO propertyValue;
CALL SYSPROC.ADMIN_CMD('REORG TABLE JIDashboardFrameProperty');

-- change column type from "varchar(1000) for bit data" to blob(20971520)
ALTER TABLE JIReportOptionsInput ADD COLUMN new_input_value blob(20971520);
UPDATE JIReportOptionsInput SET new_input_value = CAST (input_value AS blob(20971520));
COMMIT;
ALTER TABLE JIReportOptionsInput DROP COLUMN input_value;
ALTER TABLE JIReportOptionsInput RENAME COLUMN new_input_value TO input_value;
CALL SYSPROC.ADMIN_CMD('REORG TABLE JIReportOptionsInput');

-- change password column size to 750
ALTER TABLE JIJdbcDatasource ALTER COLUMN password SET DATA TYPE varchar(750);
ALTER TABLE JIReportJobRepoDest ALTER COLUMN password SET DATA TYPE varchar(750);
ALTER TABLE JIUser ALTER COLUMN password SET DATA TYPE varchar(750);
ALTER TABLE JIXMLAConnection ALTER COLUMN password SET DATA TYPE varchar(750);
ALTER TABLE JIXMLAConnection ALTER COLUMN password SET NOT NULL;

-- drop tables that are no longer used
DROP TABLE JIAdhocChartMeasure;
DROP TABLE JIAdhocColumn;
DROP TABLE JIAdhocGroup;
DROP TABLE JIAdhocTableSortField;
DROP TABLE JIAdhocXTabColumnGroup;
DROP TABLE JIAdhocXTabMeasure;
DROP TABLE JIAdhocXTabRowGroup;

create table JIAdhocDataViewBasedReports (
    adhoc_data_view_id bigint not null,
    report_id bigint not null,
    report_index integer not null,
    primary key (adhoc_data_view_id, report_index)
);

create table JIDashboardModel (
    id bigint not null,
    foundationsString clob(10000),
    resourcesString clob(10000),
    defaultFoundation integer,
    primary key (id)
);

create table JIDashboardModelResource (
    dashboard_id bigint not null,
    resource_id bigint not null,
    resource_index integer not null,
    primary key (dashboard_id, resource_index)
);

alter table JIAdhocDataViewBasedReports
    add constraint FKFFD9AFF5B22FF3B2
    foreign key (adhoc_data_view_id)
    references JIAdhocDataView;

alter table JIAdhocDataViewBasedReports
    add constraint FKFFD9AFF5830BA6DB
    foreign key (report_id)
    references JIReportUnit;

alter table JIDashboardModel
    add constraint FK8BB7D814A8BF376D
    foreign key (id)
    references JIResource;

alter table JIDashboardModelResource
    add constraint FK273EAC4230711005
    foreign key (dashboard_id)
    references JIDashboardModel;

alter table JIDashboardModelResource
    add constraint FK273EAC42F254B53E
    foreign key (resource_id)
    references JIResource;
